### PR TITLE
refactor: pointcloud_preprocessor prefix package and namespace with autoware

### PR DESCRIPTION
**Pull request by amadeuszsz**
## Description

Part of Autoware namespace refactor.

## Related links

**Parent Issue:**

- https://github.com/autowarefoundation/autoware/issues/4569

**Related PRs:**

- https://github.com/autowarefoundation/autoware.universe/pull/7983
- https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/95
- https://github.com/tier4/aip_launcher/pull/257
- https://github.com/autowarefoundation/awsim_labs_sensor_kit_launch/pull/3

## Notes for reviewers

None.

## Interface changes

None.

## Effects on system behavior

None.

### CODE REVIEW

**Comment by amadeuszsz** [comment]
memo: wait for autoware.universe merge first

**Review by technolojin — APPROVED** [review]
e2e_simulator.launch.xml was tested and the operation is confirmed.

**Review by shmpwk — APPROVED** [review]

**Comment by shmpwk** [comment]
@amadeuszsz @technolojin 
Do you think we can merge now or should we wait for https://github.com/tier4/AWSIM/pull/334 ?

**Comment by amadeuszsz** [comment]
> @amadeuszsz @technolojin Do you think we can merge now or should we wait for [tier4/AWSIM#334](https://github.com/tier4/AWSIM/pull/334) ?

@shmpwk 
Yes. Parent PR (already merged) refers only to package's namespace. Without merging this PR, `e2e_simulator.launch.xml` will fail for now on main branch since `pointcloud_preprocessor` package does not exist with this name anymore.

**Comment by shmpwk** [comment]
Thank you, I'll merge this.

**Pull request merged**
