### PR TITLE
chore: changed the package name imu_corrector to autoware_imu_corrector

### PR DESCRIPTION
**Pull request by knzo25**
## Description
Launcher counterpart of https://github.com/autowarefoundation/autoware.universe/pull/8222

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by knzo25** [comment]
@pijaro 
Can you add a reviewer? If only this PR is missing in the series of related changes, I will just merge ahead

**Comment by pijaro** [comment]
Sure, @lchojnack will take a look.

**Comment by lchojnack** [comment]
LGTM
I will merge this PR when https://github.com/autowarefoundation/autoware.universe/pull/8222 is merged

**Review by lchojnack — APPROVED** [review]

**Comment by knzo25** [comment]
@lchojnack  the parent PR was merged
:pray:

**Pull request merged**
